# Generated by Django 5.2.6 on 2025-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order", "title"]},
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.SmallIntegerField(default=0),
        ),
    ]
