# Generated by Django 5.2.6 on 2025-09-20 02:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
